version: '3.8'

services:
  auth_postgres:
    image: postgres:13
    container_name: auth_db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  hospital_postgres:
    image: postgres:13
    container_name: hospital_db
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - hospital_postgres_data:/var/lib/postgresql/data

volumes:
  auth_postgres_data:
  hospital_postgres_data: